### ISSUE TITLE
Questions about your game

### ISSUE THREAD

**Issue by remymenard** [Dannark/Dannark#1]
Hello @Dannark sorry to contact you via the issues, I really love your game. And I plan to make a game too so I can learn Flutter faster.
Did you make yourself the assets or you found them somewhere?
Also do you plan to commercialise your game or I can reuse the code as a base for a project that I will upload on the mobile stores?

**Comment by Dannark** [comment]
Hey mate, don't worries, i'm glad you liked.
The assets i did all by my self with much love hehe. I'm not an artist you know? And that's probably was the hardest part to me so yeah please, don't use the assets commercially :p

But for the code, you are free to use the way you want. I would love to play a variation of that.
I do pretend to commercialise this in a near future, but i also have to get back to my flutter studies.

You can ask me anything, my contact via email is daniel.queiroz789@gmail.com
Also, feel free to contribute for the code if you like.
